/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type Spacer = {
  _type: "spacer";
  size?: "s" | "m" | "l";
};

export type TextBlock = {
  _type: "textBlock";
  body?: RichText;
};

export type ImageOffset = {
  _type: "imageOffset";
  first?: Photo;
  second?: Photo;
  leadSide?: "left" | "right";
  offset?: "s" | "m" | "l";
  keepColumnsOnMobile?: boolean;
};

export type ImageGrid2x2 = {
  _type: "imageGrid2x2";
  images?: Array<
    {
      _key: string;
    } & Photo
  >;
  crop?: "none" | "square" | "portrait" | "landscape";
  gap?: "s" | "m" | "l";
  keepColumnsOnMobile?: boolean;
};

export type ImagePair = {
  _type: "imagePair";
  left?: Photo;
  right?: Photo;
  verticalAlign?: "top" | "bottom";
  gap?: "s" | "m" | "l";
  keepColumnsOnMobile?: boolean;
};

export type ImageFullBleed = {
  _type: "imageFullBleed";
  image?: Photo;
  fullHeight?: boolean;
};

export type ImageSingle = {
  _type: "imageSingle";
  image?: Photo;
  width?: "narrow" | "medium" | "wide";
  align?: "left" | "center" | "right";
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SocialLink = {
  _type: "socialLink";
  label?: string;
  url?: string;
};

export type Credit = {
  _type: "credit";
  label?: string;
  value?: string;
};

export type Photo = {
  _type: "photo";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  captionSecondary?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  nav?: {
    home?: string;
    projects?: string;
    about?: string;
  };
  contactEmail?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  theme?: "light" | "dark";
  indexPreviewMode?: "cursor" | "fixed";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  portrait?: Photo;
  bio?: RichText;
  clients?: Array<string>;
  contact?: {
    email?: string;
    phone?: string;
    links?: Array<
      {
        _key: string;
      } & SocialLink
    >;
  };
  representation?: Array<{
    region?: string;
    agency?: string;
    name?: string;
    email?: string;
    phone?: string;
    url?: string;
    _type: "agent";
    _key: string;
  }>;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featured?: Array<{
    project?: ProjectReference;
    image?: Photo;
    _type: "featuredItem";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  blocks?: Array<
    | ({
        _key: string;
      } & ImageSingle)
    | ({
        _key: string;
      } & ImageFullBleed)
    | ({
        _key: string;
      } & ImagePair)
    | ({
        _key: string;
      } & ImageGrid2x2)
    | ({
        _key: string;
      } & ImageOffset)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & Spacer)
  >;
  hero?: {
    mediaType?: "image" | "video";
    image?: Photo;
    videoFile?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    videoUrl?: string;
    poster?: Photo;
  };
  heroTextTone?: "light" | "dark";
  credits?: Array<
    {
      _key: string;
    } & Credit
  >;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  date?: string;
  nextProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  orderRank?: string;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Spacer
  | TextBlock
  | ImageOffset
  | ImageGrid2x2
  | ImagePair
  | ImageFullBleed
  | ImageSingle
  | RichText
  | SanityImageAssetReference
  | Seo
  | SocialLink
  | Credit
  | Photo
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | About
  | ProjectReference
  | Homepage
  | Category
  | Slug
  | SanityFileAssetReference
  | CategoryReference
  | Project
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_id == "siteSettings"][0]{  title, description, nav, contactEmail, socialLinks, theme, indexPreviewMode}
export type SettingsQueryResult =
  | {
      title: null;
      description: null;
      nav: null;
      contactEmail: null;
      socialLinks: null;
      theme: null;
      indexPreviewMode: null;
    }
  | {
      title: string | null;
      description: null;
      nav: null;
      contactEmail: null;
      socialLinks: null;
      theme: null;
      indexPreviewMode: null;
    }
  | {
      title: string | null;
      description: string | null;
      nav: null;
      contactEmail: null;
      socialLinks: null;
      theme: null;
      indexPreviewMode: null;
    }
  | {
      title: string | null;
      description: string | null;
      nav: {
        home?: string;
        projects?: string;
        about?: string;
      } | null;
      contactEmail: string | null;
      socialLinks: Array<
        {
          _key: string;
        } & SocialLink
      > | null;
      theme: "dark" | "light" | null;
      indexPreviewMode: "cursor" | "fixed" | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: projectsIndexQuery
// Query: *[_type == "project" && defined(slug.current)]  | order(orderRank asc, date desc){    _id,    title,    "slug": slug.current,    date,    "categories": categories[]->{title, "slug": slug.current},    "imageCount":   count(blocks[_type in ["imageSingle", "imageFullBleed"]])  + 2 * count(blocks[_type in ["imagePair", "imageOffset"]])  + coalesce(math::sum(blocks[_type == "imageGrid2x2"]{"n": count(images)}.n), 0)  }
export type ProjectsIndexQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  imageCount: number | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{\n  title, description, nav, contactEmail, socialLinks, theme, indexPreviewMode\n}': SettingsQueryResult;
    '*[_type == "project" && defined(slug.current)]\n  | order(orderRank asc, date desc){\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    "categories": categories[]->{title, "slug": slug.current},\n    "imageCount": \n  count(blocks[_type in ["imageSingle", "imageFullBleed"]])\n  + 2 * count(blocks[_type in ["imagePair", "imageOffset"]])\n  + coalesce(math::sum(blocks[_type == "imageGrid2x2"]{"n": count(images)}.n), 0)\n\n  }': ProjectsIndexQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
